"""Enums relacionados a exercícios"""

from enum import Enum

class ExercisseNameEnum(str, Enum):
    """Nomes padrão de exercícios de academia em ordem alfabética"""
    ABDOMINAL = "abdominal"
    ABDOMINAL_INVERTIDO = "abdominal_invertido"
    ABDOMINAL_NA_POLIA = "abdominal_na_polia"
    AGACHAMENTO = "agachamento"
    AGACHAMENTO_BULGARO = "agachamento_bulgaro"
    AGACHAMENTO_FRONTAL = "agachamento_frontal"
    AGACHAMENTO_GOBLET = "agachamento_goblet"
    AGACHAMENTO_HACK = "agachamento_hack"
    AGACHAMENTO_PISTOLA = "agachamento_pistola"
    AGACHAMENTO_SUMO = "agachamento_sumo"
    AGACHAMENTO_ZERCHER = "agachamento_zercher"
    ARRANCADA = "arrancada"
    BARRA_FIXA = "barra_fixa"
    BARRA_FIXA_PEGADA_LARGA = "barra_fixa_pegada_larga"
    BARRA_FIXA_SUPINADA = "barra_fixa_supinada"
    BARRA_FIXA_COM_PESO = "barra_fixa_com_peso"
    BURPEE = "burpee"
    CADEIRA_ABDUTORA = "cadeira_abdutora"
    CADEIRA_ADUTORA = "cadeira_adutora"
    CAMINHADA_DO_FAZENDEIRO = "caminhada_do_fazendeiro"
    CRUCIFIXO = "crucifixo"
    CRUCIFIXO_INVERSO = "crucifixo_inverso"
    CRUCIFIXO_NA_POLIA = "crucifixo_na_polia"
    DESENVOLVIMENTO = "desenvolvimento"
    DESENVOLVIMENTO_ARNOLD = "desenvolvimento_arnold"
    DESENVOLVIMENTO_COM_HALTERES = "desenvolvimento_com_halteres"
    DESENVOLVIMENTO_FRONTAL = "desenvolvimento_frontal"
    ELEVACAO_FRONTAL = "elevacao_frontal"
    ELEVACAO_LATERAL = "elevacao_lateral"
    ELEVACAO_LATERAL_CURVADO = "elevacao_lateral_curvado"
    ELEVACAO_NA_PANTURRILHA = "elevacao_na_panturrilha"
    ELEVACAO_NA_PANTURRILHA_SENTADO = "elevacao_na_panturrilha_sentado"
    ELEVACAO_PELVICA = "elevacao_pelvica"
    ENCOLHIMENTO = "encolhimento"
    ESCALADOR = "escalador"
    EXTENSAO_DE_COSTAS = "extensao_de_costas"
    EXTENSAO_DE_PERNAS = "extensao_de_pernas"
    EXTENSAO_DE_TRICEPS = "extensao_de_triceps"
    FACE_PULL = "face_pull"
    FLEXAO = "flexao"
    FLEXAO_DIAMANTE = "flexao_diamante"
    FLEXAO_DE_PERNAS = "flexao_de_pernas"
    GOOD_MORNING = "good_morning"
    LEG_PRESS = "leg_press"
    LEVANTAMENTO_TERRA = "levantamento_terra"
    LEVANTAMENTO_TERRA_DEFICIT = "levantamento_terra_deficit"
    LEVANTAMENTO_TERRA_ROMENO = "levantamento_terra_romeno"
    LEVANTAMENTO_TERRA_STIFF = "levantamento_terra_stiff"
    LEVANTAMENTO_TERRA_UMA_PERNA = "levantamento_terra_uma_perna"
    MERGULHO_NO_BANCO = "mergulho_no_banco"
    MERGULHO_PARALELA = "mergulho_paralela"
    MUSCLE_UP = "muscle_up"
    PANTURRILHA_EM_PE = "panturrilha_em_pe"
    PECK_DECK = "peck_deck"
    POLICHINELO = "polichinelo"
    PRANCHA = "prancha"
    PRANCHA_LATERAL = "prancha_lateral"
    PUXADA_ALTA = "puxada_alta"
    PUXADA_NA_POLIA = "puxada_na_polia"
    REMADA_BAIXA = "remada_baixa"
    REMADA_CAVALINHO = "remada_cavalinho"
    REMADA_CURVADA = "remada_curvada"
    REMADA_COM_BARRA = "remada_com_barra"
    REMADA_COM_HALTERES = "remada_com_halteres"
    REMADA_PENDLAY = "remada_pendlay"
    REMADA_UNILATERAL = "remada_unilateral"
    REMADA_ALTA = "remada_alta"
    ROSCA_BARRA = "rosca_barra"
    ROSCA_CONCENTRADA = "rosca_concentrada"
    ROSCA_DIRETA = "rosca_direta"
    ROSCA_MARTELO = "rosca_martelo"
    ROSCA_SCOTT = "rosca_scott"
    SALTO_NA_CAIXA = "salto_na_caixa"
    SUBIDA_NO_BANCO = "subida_no_banco"
    SUBIDA_NA_CORDA = "subida_na_corda"
    SUPERMAN = "superman"
    SUPINO = "supino"
    SUPINO_DECLINADO = "supino_declinado"
    SUPINO_FECHADO = "supino_fechado"
    SUPINO_INCLINADO = "supino_inclinado"
    SUPINO_INCLINADO_HALTERES = "supino_inclinado_halteres"
    SUPINO_RETO_HALTERES = "supino_reto_halteres"
    SWING_KETTLEBELL = "swing_kettlebell"
    THRUSTER = "thruster"
    TERRA_LEVANTAMENTO = "terra_levantamento"
    TRICEPS_CORDA = "triceps_corda"
    TRICEPS_TESTA = "triceps_testa"
    TRICEPS_COICE = "triceps_coice"
    TRICEPS_POLIA = "triceps_polia"
    TWIST_RUSSO = "twist_russo"
    V_UP = "v_up"
    AGACHAMENTO_ISOMETRICO = "agachamento_isometrico"


class ExerciseTypeEnum(str, Enum):
    """Tipo de exercício por grupo muscular ou categoria"""
    BACK = "back"
    CHEST = "chest"
    LEGS = "legs"
    ARMS = "arms"
    SHOULDERS = "shoulders"
    ABDOMEN = "abdomen"
    CARDIO = "cardio"
    STRENGTH = "strength"
    FLEXIBILITY = "flexibility"
    SPORTS = "sports"


class IntensityLevelEnum(str, Enum):
    """Nível de intensidade do exercício"""
    LOW = "low"
    MODERATE = "moderate"
    MEDIUM = "medium"  # Alias para moderate
    HIGH = "high"
    VERY_HIGH = "very_high"
